{% set name = "python-zstd" %}
{% set version = "1.5.6.6" %}
{% set zstd_version = '.'.join(version.split('.')[:-1]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zstd/zstd-{{ version }}.tar.gz
  sha256: 822c4b6575dcd30691ebde6545425b51c14ec1b2e519f684ef4b0d0616921088
  patches:
    - win.patch  # [win]

build:
  number: 0
  script:
    - export ZSTD_EXTERNAL=1  # [not win]
    - set ZSTD_EXTERNAL=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - setuptools
    - pip
    - zstd ={{ zstd_version }}
  run:
    - python

test:
  imports:
    - zstd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sergey-dryabzhinsky/python-zstd
  summary: ZSTD Bindings for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
